apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  annotations:
    # no need if not use single ip in loadbalancer
    metallb.universe.tf/allow-shared-ip: 'xx.xx.xx.xx'
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-http-service
  annotations:
    # no need if not use single ip in loadbalancer
    metallb.universe.tf/allow-shared-ip: 'xx.xx.xx.xx'
spec:
  type: LoadBalancer
  ports:
    - targetPort: traefik-http
      port: 80
  selector:
    app: traefik
