apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-service
  annotations:
    # no need if not use single ip in loadbalancer
    metallb.universe.tf/allow-shared-ip: 'xx.xx.xx.xx'
spec:
  type: LoadBalancer
  ports:
    - targetPort: 9090
      port: 9090
  selector:
    app: prometheus
